version: '3'
services:
  redmine:
    image: redmine:3.4
    container_name: redmine
    volumes:
      - ./redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./redmine/files:/usr/src/redmine/files
    environment:
      - REDMINE_DB_MYSQL=mariadb
      - REDMINE_DB_PASSWORD=your-password
    ports:
      - "3000:3000"
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=redmine
      - MYSQL_ROOT_PASSWORD=your-password
    ports:
     - "3306:3306"
    restart: always

  dbadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dbadmin
    depends_on:
      - mariadb
    links:
      - mariadb:db
    restart: always

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - '80:80'
      - '443:443'
      - '8443:8443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    depends_on:
      - dbadmin
      - redmine
    links:
      - dbadmin
      - redmine
    restart: always

